#!/bin/bash

echo "🧪 Testing deployed contract on testnet..."
echo ""
echo "Contract: ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.vault-core"
echo ""
echo "📍 View on Stacks Explorer:"
echo "   https://explorer.hiro.so/address/ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM?chain=testnet"
echo ""
echo "🔍 Test your contract functions:"
echo ""
echo "Option 1: Use Stacks Explorer"
echo "   1. Visit the contract address above"
echo "   2. Go to 'Functions' tab"
echo "   3. Call functions directly in your browser"
echo ""
echo "Option 2: Use local console with remote data"
echo "   clarinet console --enable-remote-data --remote-data-api-url https://api.testnet.hiro.so"
echo ""
echo "Option 3: Use Stacks CLI"
echo "   npm install -g @stacks/cli"
echo "   stx call-contract-func <function-name> --testnet"
echo ""
echo "📝 Quick function tests to verify:"
echo ""
echo "1. Read-only functions (no STX needed):"
echo "   - get-contract-version"
echo "   - get-total-deposits"
echo "   - get-protocol-stats"
echo ""
echo "2. Write functions (requires testnet STX):"
echo "   - deposit (amount: u1000000)"
echo "   - get-user-deposit (check balance)"
echo "   - borrow (amount: u500000, rate: u10, term: u30)"
echo "   - repay"
echo ""
echo "Get testnet STX faucet:"
echo "   https://explorer.hiro.so/sandbox/faucet?chain=testnet"
echo ""
