#!/bin/bash

echo "🧪 BitFlow Finance - Testnet Function Testing"
echo "============================================"
echo ""
echo "Contract deployed at: ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.vault-core"
echo ""
echo "Testing options:"
echo ""
echo "1️⃣  Interactive Console Testing (Recommended)"
echo "   Run: clarinet console --testnet"
echo "   Then test functions interactively"
echo ""
echo "2️⃣  Stacks Explorer Testing"
echo "   Visit: https://explorer.hiro.so/txid/YOUR_TX_ID?chain=testnet"
echo "   View your deployment and call functions"
echo ""
echo "3️⃣  Manual Function Testing"
echo ""
echo "📝 Test Sequence:"
echo ""
echo "Test 1: Deposit STX"
echo "  (contract-call? .vault-core deposit u1000000)"
echo "  Expected: (ok true)"
echo ""
echo "Test 2: Check deposit balance"
echo "  (contract-call? .vault-core get-user-deposit tx-sender)"
echo "  Expected: u1000000"
echo ""
echo "Test 3: Borrow against collateral"
echo "  (contract-call? .vault-core borrow u500000 u10 u30)"
echo "  Expected: (ok true)"
echo ""
echo "Test 4: Check loan details"
echo "  (contract-call? .vault-core get-user-loan tx-sender)"
echo "  Expected: (some { amount: u500000, interest-rate: u10, ... })"
echo ""
echo "Test 5: Withdraw (should fail - collateral locked)"
echo "  (contract-call? .vault-core withdraw u1000000)"
echo "  Expected: Error (collateral in use)"
echo ""
echo "Test 6: Repay loan"
echo "  (contract-call? .vault-core repay)"
echo "  Expected: (ok { principal: u500000, interest: ..., total: ... })"
echo ""
echo "Test 7: Withdraw after repayment"
echo "  (contract-call? .vault-core withdraw u1000000)"
echo "  Expected: (ok true)"
echo ""
echo "🚀 Start testing with:"
echo "   clarinet console --testnet"
echo ""
